<?php
    $this->plugin('translate')->setTranslatorTextDomain('playgroundtranslate');
    $user = $this->user;
    $locales = $this->locales;
    $translates = $this->translates;

    $form = $this->form;
    $form->prepare();
    $form->get('submit')->setLabel($this->translate('validate'));
?>


<div class="row translate">
    <div class="col-md-9">
    <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><?php echo $this->translate('upload translate'); ?></h3>
        </div>
        <div class="panel-body">
            <?php echo $this->form()->openTag($form);  ?>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('uploadTranslate')); ?>
                <?php echo $this->formFile($form->get('uploadTranslate')->setAttribute('class', 'form-control')); ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('locale')); ?>
                <?php echo $this->formSelect($form->get('locale')->setAttribute('class', 'form-control')); ?>
            </div>
            <div class='pull-right margin-right30'>
                <?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-success')) ?>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
    <hr />
    <form action="/admin/translate/update" method="post">
        <div class="panel panel-danger">
            <div class="panel-heading">
              <h3 class="panel-title"><?php echo $this->translate('update translate'); ?></h3>
            </div>
            <div class="panel-body">
                <div class='pull-right margin-right30'>
                    <?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-success')) ?>
                </div>
                <div class="clearfix"></div>
                <table class="table">
                    <thead>
                        <tr>
                            <td>clé </td>
                            <?php foreach (array_keys($translates) as $locale) : ?>
                                 <td><?php echo $locale; ?></td>
                            <?php endforeach ; ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($keys as $key) : ?>
                        <tr>
                            <td> <?php echo $key; ?></td>
                            <?php foreach (array_keys($translates) as $locale) : ?>
                                <td>
                                    <textarea class="form-control" rows="3" name="translate[<?php echo $locale ?>][<?php echo $key ?>]"><?php echo !empty($translates[$locale][$key])?$translates[$locale][$key]:''; ?></textarea>  
                                </td>
                            <?php endforeach; ?>
                        </tr>
                        <?php endforeach ; ?>
                    </tbody>
                 </table>
            </div>
        </div>
    </form>
    </div>
     <div class="col-md-3">
        <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title"><?php echo $this->translate('history'); ?></h3>
        </div>
        <div class="panel-body">
            <div class="list-group">
                <?php foreach ($this->historicals as $historical) : ?>
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">
                            <?php $date = $historical['datetime']; ?>
                            <?php $dateFormat = $this->translate('date_format'); ?>
                            <?php if(strpos('H:i:s', $dateFormat) === false) : ?>
                                <?php $dateFormat = 'H:i:s d/m/Y'; ?>
                            <?php endif; ?>
                            <?php echo $date->format($dateFormat); ?>
                        </h4>
                        <p class="list-group-item-text">
                        <?php echo $this->translate('New import of translate'); ?>  <?php echo $this->translate($this->localesForm[$historical['locale']]); ?>
                        </p>
                    </a>
              <?php endforeach; ?>
            </div>
        </div>
    </div>
    </div>
</div>
